/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CreateJobInputSchedule } from './createJobInputSchedule';
import type { CreateJobTool } from './createJobTool';

export interface CreateJobInput {
  name: string;
  /** @nullable */
  schedule: CreateJobInputSchedule;
  tools: CreateJobTool[];
}
