/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

export type CreateEmailToolType = (typeof CreateEmailToolType)[keyof typeof CreateEmailToolType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateEmailToolType = {
    email: 'email',
} as const;
