/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CreateScraperTool } from './createScraperTool';
import type { CreateEmailTool } from './createEmailTool';

export type CreateJobTool = CreateScraperTool | CreateEmailTool;
