/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { EmailToolTargetName } from './emailToolTargetName';

export type CreateEmailToolTargetsItem = {
    body?: string;
    subject?: string;
    target: EmailToolTargetName;
};
