/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

export type CreateScraperToolType = (typeof CreateScraperToolType)[keyof typeof CreateScraperToolType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateScraperToolType = {
    scraper: 'scraper',
} as const;
