/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

export type CreateJobInputScheduleType = typeof CreateJobInputScheduleType[keyof typeof CreateJobInputScheduleType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateJobInputScheduleType = {
  once: 'once',
  daily: 'daily',
  weekly: 'weekly',
  monthly: 'monthly',
  yearly: 'yearly',
} as const;
