/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CreateJobInputScheduleType } from './createJobInputScheduleType';

/**
 * @nullable
 */
export type CreateJobInputSchedule = {
  /** @nullable */
  endDate: string | null;
  startDate: string;
  type: CreateJobInputScheduleType;
} | null;
