/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CreateScraperToolTargetsItem } from './createScraperToolTargetsItem';
import type { CreateScraperToolType } from './createScraperToolType';

export interface CreateScraperTool {
    /** @minItems 1 */
    keywords: string[];
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    maxPages: number;
    targets: CreateScraperToolTargetsItem[];
    type: CreateScraperToolType;
}
