/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CreateEmailToolTargetsItem } from './createEmailToolTargetsItem';
import type { CreateEmailToolType } from './createEmailToolType';

export interface CreateEmailTool {
    body?: string;
    subject?: string;
    targets: CreateEmailToolTargetsItem[];
    type: CreateEmailToolType;
}
