/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { EmailToolTarget } from './emailToolTarget';
import type { EmailToolTypeProperty } from './emailToolTypeProperty';

export interface EmailTool {
    body?: string;
    subject?: string;
    targets: EmailToolTarget[];
    toolId: string;
    type: EmailToolTypeProperty;
}
