/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

export type EmailToolType = typeof EmailToolType[keyof typeof EmailToolType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EmailToolType = {
  email: 'email',
} as const;
