/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { EnrichedJobScheduleType } from './enrichedJobScheduleType';

/**
 * @nullable
 */
export type EnrichedJobSchedule = {
  /** @nullable */
  endDate: string | null;
  /** @nullable */
  lastRun: string | null;
  /** @nullable */
  nextRun: string | null;
  startDate: string;
  type: EnrichedJobScheduleType;
} | null;
