/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

export type EnrichedJobScheduleType = typeof EnrichedJobScheduleType[keyof typeof EnrichedJobScheduleType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnrichedJobScheduleType = {
  once: 'once',
  daily: 'daily',
  weekly: 'weekly',
  monthly: 'monthly',
  yearly: 'yearly',
} as const;
