/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionScraperDescription } from './executionScraperDescription';
import type { ExecutionScraperInformation } from './executionScraperInformation';

/**
 * @nullable
 */
export type ExecutionScraperPageContent = {
  descriptions: ExecutionScraperDescription[];
  informations: ExecutionScraperInformation[];
  title: string;
  url: string;
} | null;
