/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionScrapedItemError } from './executionScrapedItemError';
import type { ScraperToolTargetName } from './scraperToolTargetName';

export interface ExecutionScrapedItemFail {
  error: ExecutionScrapedItemError;
  listingKey: string;
  ok: boolean;
  source: ScraperToolTargetName;
  url: string;
}
