/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

export type ExecutionScraperToolType = typeof ExecutionScraperToolType[keyof typeof ExecutionScraperToolType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExecutionScraperToolType = {
  scraper: 'scraper',
} as const;
