/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionEmailToolTargetResult } from './executionEmailToolTargetResult';
import type { EmailToolTargetName } from './emailToolTargetName';

export interface ExecutionEmailToolTarget {
    body?: string;
    results: ExecutionEmailToolTargetResult[];
    subject?: string;
    target: EmailToolTargetName;
    targetId: string;
}
