/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionScrapedItemSuccessFields } from './executionScrapedItemSuccessFields';
import type { ScraperToolTargetName } from './scraperToolTargetName';

export interface ExecutionScrapedItemSuccess {
  fields?: ExecutionScrapedItemSuccessFields;
  listingKey: string;
  ok: boolean;
  /** @nullable */
  postedAt?: string | null;
  source: ScraperToolTargetName;
  text: string;
  title: string;
  url: string;
}
