/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionScrapedItemSuccess } from './executionScrapedItemSuccess';
import type { ExecutionScrapedItemFail } from './executionScrapedItemFail';

export type ExecutionScrapedItem = ExecutionScrapedItemSuccess | ExecutionScrapedItemFail;
