/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionEmailToolTarget } from './executionEmailToolTarget';
import type { ExecutionEmailToolType } from './executionEmailToolType';

export interface ExecutionEmailTool {
    body?: string;
    subject?: string;
    targets: ExecutionEmailToolTarget[];
    toolId: string;
    type: ExecutionEmailToolType;
}
