/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionScraperToolTarget } from './executionScraperToolTarget';
import type { ExecutionScraperToolType } from './executionScraperToolType';

export interface ExecutionScraperTool {
  /** @minItems 1 */
  keywords?: string[];
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  maxPages?: number;
  targets: ExecutionScraperToolTarget[];
  toolId: string;
  type: ExecutionScraperToolType;
}
