/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ExecutionEmailToolTargetResultContent = {
    body: string;
    email: string;
    subject: string;
} | null;
