/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionScraperToolTarget } from './executionScraperToolTarget';
import type { ExecutionEmailToolTarget } from './executionEmailToolTarget';

export type ExecutionToolTarget = ExecutionScraperToolTarget | ExecutionEmailToolTarget;
