/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ExecutionScheduleType = (typeof ExecutionScheduleType)[keyof typeof ExecutionScheduleType] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExecutionScheduleType = {
    once: 'once',
    daily: 'daily',
    weekly: 'weekly',
    monthly: 'monthly',
    yearly: 'yearly',
} as const;
