/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionSchedule } from './executionSchedule';
import type { ExecutionTool } from './executionTool';

export interface Execution {
  executionId: string;
  schedule: ExecutionSchedule;
  /** @minItems 1 */
  tools: ExecutionTool[];
}
