/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionScrapedItem } from './executionScrapedItem';
import type { ExecutionJobItemMatch } from './executionJobItemMatch';
import type { ExecutionScrapedItemPrefilter } from './executionScrapedItemPrefilter';

export interface ExecutionJobItemRow {
  listing: ExecutionScrapedItem;
  match?: ExecutionJobItemMatch;
  prefilter?: ExecutionScrapedItemPrefilter;
}
