/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionScheduleType } from './executionScheduleType';

export interface ExecutionSchedule {
    delegatedAt: string;
    /** @nullable */
    finishedAt: string | null;
    /** @nullable */
    type: ExecutionScheduleType;
}
