/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionScraperTargetResult } from './executionScraperTargetResult';
import type { ScraperToolTargetName } from './scraperToolTargetName';

export interface ExecutionScraperToolTarget {
  /** @minItems 1 */
  keywords?: string[];
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  maxPages?: number;
  results: ExecutionScraperTargetResult[];
  target: ScraperToolTargetName;
  targetId: string;
}
