/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { TargetResultError } from './targetResultError';
import type { ExecutionScraperPageContent } from './executionScraperPageContent';

export interface ExecutionScraperTargetResult {
  error: TargetResultError;
  result: ExecutionScraperPageContent;
}
