/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Execution } from './execution';
import type { JobSchedule } from './jobSchedule';
import type { Tool } from './tool';

export interface Job {
  createdAt: string;
  executions?: Execution[];
  id: string;
  name: string;
  schedule: JobSchedule;
  /** @minItems 1 */
  tools: Tool[];
  /** @nullable */
  updatedAt: string | null;
  userId: string;
}
