/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { JobFinishedEventType } from './jobFinishedEventType';

export interface JobFinishedEvent {
  executionId: string;
  finishedAt: string;
  jobId: string;
  type: JobFinishedEventType;
  userId: string;
}
