/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

export type JobFinishedEventType = (typeof JobFinishedEventType)[keyof typeof JobFinishedEventType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobFinishedEventType = {
    'job-finished': 'job-finished',
} as const;
