/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { JobFailedEventType } from './jobFailedEventType';

export interface JobFailedEvent {
  executionId: string;
  failedAt: string;
  jobId: string;
  type: JobFailedEventType;
  userId: string;
}
