/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { JobScheduleType } from './jobScheduleType';

/**
 * @nullable
 */
export type JobSchedule = {
    /** @nullable */
    endDate: string | null;
    startDate: string;
    type: JobScheduleType;
} | null;
