/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

export type JobTargetFinishedEventType = (typeof JobTargetFinishedEventType)[keyof typeof JobTargetFinishedEventType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobTargetFinishedEventType = {
    'job-target-finished': 'job-target-finished',
} as const;
