/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionSchedule } from './executionSchedule';
import type { ExecutionToolTarget } from './executionToolTarget';
import type { Tool } from './tool';
import type { JobTargetFinishedEventType } from './jobTargetFinishedEventType';

export interface JobTargetFinishedEvent {
  executionId: string;
  jobId: string;
  schedule: ExecutionSchedule;
  target: ExecutionToolTarget;
  tool: Tool;
  type: JobTargetFinishedEventType;
  userId: string;
}
