/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutionToolTargetResult } from './executionToolTargetResult';
import type { ToolTargetName } from './toolTargetName';
import type { JobTargetFinishedEventType } from './jobTargetFinishedEventType';

export interface JobTargetFinishedEvent {
  jobId: string;
  results: ExecutionToolTargetResult[];
  target: ToolTargetName;
  targetId: string;
  toolId: string;
  type: JobTargetFinishedEventType;
  userId: string;
}
