/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

export type ScraperToolType = (typeof ScraperToolType)[keyof typeof ScraperToolType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScraperToolType = {
    scraper: 'scraper',
} as const;
