/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

export type ScraperToolTargetName = (typeof ScraperToolTargetName)[keyof typeof ScraperToolTargetName];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScraperToolTargetName = {
    'jobs-ch': 'jobs-ch',
} as const;
