/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ScraperToolTargetName } from './scraperToolTargetName';

export interface ScraperToolTarget {
    /** @minItems 1 */
    keywords?: string[];
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    maxPages?: number;
    target: ScraperToolTargetName;
    targetId: string;
}
