/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ScraperToolTarget } from './scraperToolTarget';
import type { ScraperToolTypeProperty } from './scraperToolTypeProperty';

export interface ScraperTool {
    /** @minItems 1 */
    keywords: string[];
    /**
     * @minimum 0
     * @exclusiveMinimum
     */
    maxPages: number;
    targets: ScraperToolTarget[];
    toolId: string;
    type: ScraperToolTypeProperty;
}
