/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type TargetResultError = {
    message: string;
} | null;
