/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ScraperTool } from './scraperTool';
import type { EmailTool } from './emailTool';

export type Tool = ScraperTool | EmailTool;
