/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ScraperToolTargetName } from './scraperToolTargetName';
import type { EmailToolTargetName } from './emailToolTargetName';

export type ToolTargetName = ScraperToolTargetName | EmailToolTargetName;
