/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateJobScraperTarget } from './updateJobScraperTarget';
import type { UpdateJobScraperToolType } from './updateJobScraperToolType';

export interface UpdateJobScraperTool {
  /** @minItems 1 */
  keywords?: string[];
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  maxPages?: number;
  targets: UpdateJobScraperTarget[];
  toolId?: string;
  type: UpdateJobScraperToolType;
}
