/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateJobEmailTarget } from './updateJobEmailTarget';
import type { UpdateJobEmailToolType } from './updateJobEmailToolType';

export interface UpdateJobEmailTool {
  body?: string;
  subject?: string;
  targets: UpdateJobEmailTarget[];
  toolId?: string;
  type: UpdateJobEmailToolType;
}
