/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateJobInputScheduleType } from './updateJobInputScheduleType';

/**
 * @nullable
 */
export type UpdateJobInputSchedule = {
  /** @nullable */
  endDate: string | null;
  startDate: string;
  type: UpdateJobInputScheduleType;
} | null;
