/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */
import type { JobSchedule } from './jobSchedule';
import type { UpdateJobTool } from './updateJobTool';

export interface UpdateJobInput {
  name: string;
  runJob: boolean;
  schedule: JobSchedule;
  tools: UpdateJobTool[];
}
